baseURL = "https://zhangjunfelix.github.io/thinkwrite1/"
languageCode = "en-us"
title = "Critical Thinking & English Writing I"
copyright = "Zhang Jun"

[params]
  mode = "auto" # light/dark/auto
  subtitle = "Welcome to Critical Thinking & English Writing I"
  mathjax = false
  katex = false
  useCDN = false
  customCSS = ["css/custom.css"]

# Top navigation

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Syllabus"
  pageRef = "/syllabus"
  weight = 2

[[menu.main]]
  name = "Introduction to Description"
  pageRef = "/introdescription"
  weight = 3

[[menu.main]]
  name = "Show, Don't Tell"
  pageRef = "/shownottell"
  weight = 4

[[menu.main]]
  name = "Sensory Imagery & Precision"
  pageRef = "/sensoryimagery"
  weight = 5

[[menu.main]]
  name = "Person Description"
  pageRef = "/persondescription"
  weight = 6

[[menu.main]]
  name = "Place Description"
  pageRef = "/placedescription"
  weight = 7

[[menu.main]]
  name = "Organization & Coherence"
  pageRef = "/organizationcoherence"
  weight = 8

[[menu.main]]
  name = "Revision & Submission"
  pageRef = "/revisionsubmission"
  weight = 9

[[menu.main]]
  name = "Introduction to Narration"
  pageRef = "/intronarration"
  weight = 10

[[menu.main]]
  name = "Memoir Project"
  pageRef = "/memoirproject"
  weight = 11

[[menu.main]]
  name = "Memoir Part 1"
  pageRef = "/memoir1"
  weight = 12

[[menu.main]]
  name = "Memoir Part 2"
  pageRef = "/memoir2"
  weight = 13

[[menu.main]]
  name = "Story Elements"
  pageRef = "/storyelements"
  weight = 14

[[menu.main]]
  name = "Plot Structure"
  pageRef = "/plot"
  weight = 15

[[menu.main]]
  name = "Point of View & Voice"
  pageRef = "/pov"
  weight = 16

[[menu.main]]
  name = "Scene vs. Summary"
  pageRef = "/scene"
  weight = 17

[[menu.main]]
  name = "Dialogue & Character"
  pageRef = "/dialogue"
  weight = 18

[[menu.main]]
  name = "Tension & Emotional Impact"
  pageRef = "/tension"
  weight = 19

[[menu.main]]
  name = "Personal Narrative vs. Fiction"
  pageRef = "/personalnarrativefiction"
  weight = 20

[module]
  [[module.imports]]
    path = "github.com/athul/archie"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]
